import exp from 'constants'
import Head from 'next/head'
import Image from 'next/image'
import { ReactNode, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [board, setBoard] = useState(new Array(9).fill(null));

  console.log(board)
  function move(index:number){
    const newboard = [...board]
    newboard[index] = "X"
    console.log(index)
    setBoard(newboard)

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TicTacToe</title>
        <meta name="TicTacToeGame" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>TicTacToe</h1>
    <div className={styles.boardbox}>{board.map((item,index) => (
    <Grid key={index} onClick={() => move(index)} >
      {item}
    </Grid>))
    }</div>
    

      </div>

      )

    }

 
function Grid(props:{children?:ReactNode,onClick?:()=>void}){
 
  return <div className={styles.board} onClick={props.onClick}>{props.children}</div>


}